'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import {
  Keyboard, Clipboard, Camera, Globe, AppWindow, Search,
  Shield, Share2, EyeOff, Calendar, HardDrive,
  CheckCircle2, Scale, Quote, Star
} from 'lucide-react';

const HomePage = () => {
  const [activeIndex, setActiveIndex] = useState(0);

  const featureList = [
    { name: 'Keystrokes', icon: '⌨️', image: '/assets/images/best-free-keylogger-applications (1).png' },
    { name: 'Clipboard', icon: '📋', image: '/assets/images/best-free-keylogger-applications (2).png' },
    { name: 'Screenshots', icon: '📸', image: '/assets/images/screenshots-view.png' },
    { name: 'Internet', icon: '🌐', image: '/assets/images/best-free-keylogger-applications (4).png' },
    { name: 'Applications', icon: '💻', image: '/assets/images/best-free-keylogger-applications.png' }
  ];

  const mainFeatures = [
    { icon: <Keyboard size={24} />, text: "Keystroke Logging", desc: "Capture every character typed.", color: "bg-blue-500" },
    { icon: <Clipboard size={24} />, text: "Clipboard Tracking", desc: "Sync and monitor copied data.", color: "bg-orange-500" },
    { icon: <Camera size={24} />, text: "Visual Capture", desc: "Automated desktop screenshots.", color: "bg-purple-500" },
    { icon: <Globe size={24} />, text: "Web Activity", desc: "Log visited URLs and search history.", color: "bg-emerald-500" },
    { icon: <AppWindow size={24} />, text: "App Oversight", desc: "Monitor active window processes.", color: "bg-cyan-500" },
    { icon: <Search size={24} />, text: "Smart Filter", desc: "Intelligent data parsing.", color: "bg-indigo-500" },
  ];



  const bentoCards = [
    {
      title: "Monitor everything",
      desc: "Best Free Keylogger can record all keystrokes, internet activity, clipboard activity, and local application usage while capturing screenshots of on-going activities on the target computer at set intervals.",
      icon: <Shield className="text-emerald-500" />,
      bg: "bg-emerald-500/10",
      image: "/assets/images/best-free-keylogger-applications.png"
    },
    {
      title: "Friendly report viewer",
      desc: "Best Free Keylogger is equipped with an easy-to-use, but extremely powerful report viewer and screenshot viewer. With unique \"Smart-Read\" feature on Best Free Keylogger, keystroke reports become highly user-friendly and easy to read.",
      icon: <Search className="text-indigo-500" />,
      bg: "bg-indigo-500/10",
      image: "/assets/images/best-free-keylogger-applications (1).png",
      featured: true
    },
    {
      title: "Multiple delivery methods",
      desc: "Reports generated by Best Free Keylogger can be emailed or uploaded to an FTP server of your choice. You can also configure Best Free Keylogger to send reports to a computer on the same LAN or to copy logs to a USB drive automatically when plugged in.",
      icon: <Share2 className="text-blue-500" />,
      bg: "bg-blue-500/10",
      image: "/assets/images/best-free-keylogger-applications (2).png"
    },
    {
      title: "Highly Configurable",
      desc: "Flexible scheduling and user filtering.",
      icon: <EyeOff className="text-violet-500" />,
      bg: "bg-violet-500/10",
      image: "/assets/images/best-free-keylogger-applications (3).png"
    },
    {
      title: "Find data instantly",
      desc: "Best Free Keylogger's Report Viewer is packed with seach filters that make finding what you want amazingly quick and exteremly extremely easy.",
      icon: <Calendar className="text-amber-500" />,
      bg: "bg-amber-500/10",
      image: "/assets/images/best-free-keylogger-applications (4).png"
    },
    {
      title: "Safe and secure",
      desc: "Best Free Keylogger works invisibly in the background, and it is password protected. Thefore, only the user who installed the software can see or open it using the password. Even antivirus programs cannot detect the software and all log files are encrypted for the security of your information.",
      icon: <HardDrive className="text-cyan-500" />,
      bg: "bg-cyan-500/10",
      image: "/assets/images/best-free-keylogger-applications.png"
    }
  ];

  const targetAudience = ["System Administrators", "Your Business", " Parents", "Schools", "Internet Cafes", "Personal Users"];

  const testimonials = [
    { name: "John D.", role: "IT Manager", text: "I use Best Free Keylogger to watch my kid's internet behavior. Now I know exactly what he is doing on the internet. I would highly recommend this software to any parent who would like to keep an eye on thier kids. Ensures your kids stay out of trouble and away from predators." },
    { name: "Sarah L.", role: "Parent", text: "After trying several of products I chose Best Free Keylogger. It's very easy to install and simple to use. It monitors everything I want. And it's the only software that works with Firefox, Chrome Opera, IE and all other browsers. I'm so appreciative to service team. They really have excellent customer service.." }
  ];

  return (
    <main className="bg-slate-50 min-h-screen py-16">

      {/* ===== FEATURE TABS ===== */}
      <section className="max-w-6xl mx-auto px-6 mb-24">
        <div className="flex flex-wrap justify-center gap-3 mb-10">
          {featureList.map((feature, index) => (
            <button
              key={feature.name}
              onClick={() => setActiveIndex(index)}
              className={`px-6 py-3 rounded-full text-sm font-semibold transition ${index === activeIndex
                ? 'bg-slate-900 text-white'
                : 'bg-white text-slate-600 hover:bg-slate-100'
                }`}
            >
              {feature.icon} {feature.name}
            </button>
          ))}
        </div>

        <div className="max-w-5xl mx-auto aspect-video rounded-3xl overflow-hidden shadow-xl bg-white">
          <img
            src={featureList[activeIndex].image}
            className="w-full h-full object-cover"
            alt="feature"
          />
        </div>
      </section>

      {/* ===== MODERN FEATURE CARDS ===== */}
      <section className="max-w-6xl mx-auto px-6 mb-24">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-center mb-12">
            Features of Best Free Keylogger
          </h2>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">

          {mainFeatures.map((item, idx) => (
            <div
              key={idx}
              className="group relative p-px rounded-3xl bg-linear-to-br from-slate-200/40 to-slate-300/40   transition-all duration-500"
            >
              <div className="relative h-full bg-white/80 backdrop-blur-xl rounded-3xl p-8 border border-white/40  transition">

                {/* glow */}
                <div className="absolute inset-0 rounded-3xl opacity-0  blur-2xl bg-linear-to-br from-blue-400/20 to-indigo-400/20 transition" />

                {/* icon */}
                <div className={`relative z-10 w-14 h-14 flex items-center justify-center rounded-2xl ${item.color} text-white mb-6  transition`}>
                  {item.icon}
                </div>

                <h3 className="relative z-10 text-xl font-semibold text-slate-900 mb-2  transition">
                  {item.text}
                </h3>

                <p className="relative z-10 text-slate-500 text-sm leading-relaxed">
                  {item.desc}
                </p>

              </div>



            </div>

          ))}
          <div className="md:col-span-2 lg:col-span-3 flex justify-center mt-4">
            <Link
              href="/features"
              className="bg-slate-900 text-white py-3 px-6 rounded-full hover:bg-slate-700 transition"
            >
              Learn More
            </Link>
          </div>
        </div>
      </section>

      {/* ===== BENTO GRID (MODERN) ===== */}
      <section className="max-w-6xl mx-auto px-6 mb-24">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">

          {bentoCards.map((card, idx) => (
            <div
              key={idx}
              className={`group relative p-px rounded-3xl ${card.featured
                ? "bg-linear-to-br from-indigo-500 to-blue-500"
                : "bg-linear-to-br from-slate-200/40 to-slate-300/40"
                }`}
            >
              <div className={`relative h-full rounded-3xl p-7 backdrop-blur-xl border ${card.featured
                ? "bg-slate-900 text-white border-white/10"
                : "bg-white/80 border-white/40 shadow-lg hover:shadow-xl"
                }`}>

                <div className={`w-12 h-12 flex items-center justify-center rounded-xl mb-5 ${card.featured ? "bg-white/10" : card.bg
                  }`}>
                  {card.icon}
                </div>

                <h3 className={`text-lg font-semibold mb-2 ${card.featured ? "text-white" : "text-slate-900"
                  }`}>
                  {card.title}
                </h3>

                <p className={`text-sm mb-6 ${card.featured ? "text-slate-300" : "text-slate-500"
                  }`}>
                  {card.desc}
                </p>

                <img
                  src={card.image}
                  className="rounded-xl h-32 w-full object-cover "
                  alt={card.title}
                />

              </div>
            </div>
          ))}

        </div>
      </section>

      {/* ===== TESTIMONIALS ===== */}
      <section className="max-w-6xl mx-auto px-6">
        <h2 className="text-4xl font-bold text-center mb-12">
          Trusted by Thousands
        </h2>

        <div className="grid lg:grid-cols-3 gap-6">

          <div className="space-y-6">
            <div className="bg-white p-6 rounded-3xl shadow-sm">
              {targetAudience.map((item) => (
                <div key={item} className="flex items-center gap-2 mb-2">
                  <CheckCircle2 size={16} />
                  {item}
                </div>
              ))}
            </div>

            <div className="relative overflow-hidden rounded-3xl border border-slate-700 bg-linear-to-br from-slate-900 via-slate-800 to-slate-900 p-6 text-white shadow-lg">
              <div className="absolute -top-10 -right-10 h-28 w-28 rounded-full bg-emerald-400/20 blur-2xl" />

              <div className="relative z-10">
                <div className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-white/10">
                  <Scale size={20} />
                </div>

                <h3 className="text-lg font-semibold tracking-tight">
                  Is It Legal to Use a Keylogger?
                </h3>

                <p className="mt-3 text-sm leading-relaxed text-slate-200">
                  Using Best Free Keylogger is legal as long as you own the computer or have administrative permission from the computer owner.
                </p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-2 space-y-6">
            {testimonials.map((t, i) => (
              <div key={i} className="bg-white p-6 rounded-3xl shadow-sm">
                <Quote size={32} className="text-slate-200 mb-3" />
                <p className="italic mb-4">"{t.text}"</p>

                <div className="flex justify-between items-center">
                  <div>
                    <div className="font-bold">{t.name}</div>
                    <div className="text-xs text-slate-400">{t.role}</div>
                  </div>

                  <div className="flex">
                    {[...Array(5)].map((_, i) => (
                      <Star key={i} size={14} className="text-amber-400" />
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* ===== AWARDS ===== */}
      <section className="max-w-6xl mx-auto px-6 mt-24">
        <p className="text-center text-slate-400 text-sm font-medium mb-10 uppercase tracking-widest">
          Recognized for Excellence
        </p>

        <div className="flex flex-wrap justify-center items-center gap-12 opacity-50 grayscale hover:grayscale-0 transition-all duration-500">
          {[1, 2, 3, 4, 5, 6, 7].map((num) => (
            <img
              key={num}
              src={`/assets/awards/awardlogo${num}.png`}
              alt="Award logo"
              className="h-10 w-auto object-contain"
            />
          ))}
        </div>
      </section>

    </main>
  );
};

export default HomePage;