import FaqAnswerPage from '../_components/FaqAnswerPage';

const Page = () => {
  return (
    <FaqAnswerPage
      title="How to import and view logs"
      question="How do I view reports received via Email, LAN, FTP, or USB?"
      answer={[
        'The method of viewing reports after receiving them via Email, LAN, FTP, or USB depends on the file format. There are two file formats available for reports generated by Best Free Keylogger.',
        'HTML File: Reports received as HTML files have a .htm file extension, and they can be opened in any major web browser, such as Chrome, Edge, or Firefox.',
        'The report and supporting files may be in a ZIP archive if it was emailed or you chose to protect the report with a password. In that case, unzip the archive before opening the .htm file.',
        'Encrypted File: Reports received as encrypted files have a .kelgfile extension, and they can be opened only by importing to Best Free Keylogger or Best Free Keylogger Report Viewer.',
        'How to import encrypted report files:',
        '1. Go to Import on the main toolbar.',
        '2. Click Add Files to browse and stage the log file for importing.',
        '3. Click Import to import the staged logs to Best Free Keylogger.',
        '4. Close the Import Log Files window and select the date of the report on the calendar.',
        '5. Click Load Report to view the logs pertaining to that date.',
        'Note: Best Free Keylogger offers the ability to encrypt your log files with a custom private key. If the log files you are trying to import were encrypted with a custom private key, you have to enter the same private key when importing them to Best Free Keylogger.'
      ]}
    />
  );
};

export default Page;
